apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-sa
  namespace: demo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-minimal-role
  namespace: demo-app
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-minimal-binding
  namespace: demo-app
subjects:
- kind: ServiceAccount
  name: argocd-sa
  namespace: demo-app
roleRef:
  kind: Role
  name: argocd-minimal-role
  apiGroup: rbac.authorization.k8s.io
